version: '3.7'

services:
  soa-eureka-server:
    image: teuzed/soa-eureka-server:latest
    container_name: soa-eureka-server
    ports:
      - "8761:8761"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-eureka-server
  
  soa-gateway-microservice:
    image: teuzed/soa-gateway-microservice:latest
    container_name: soa-gateway-microservice
    ports:
      - "8099:8099"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-gateway-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka

  soa-user-microservice:
    image: teuzed/soa-user-microservice:latest
    container_name: soa-user-microservice
    ports:
      - "8085:8085"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-user-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka

  soa-auth-microservice:
    image: teuzed/soa-auth-microservice:latest
    container_name: soa-auth-microservice
    ports:
      - "8086:8086"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-auth-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka    

  soa-product-microservice:
    image: teuzed/soa-product-microservice:latest
    container_name: soa-product-microservice
    ports:
      - "8081:8081"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-product-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka    
        
  soa-payment-microservice:
    image: teuzed/soa-payment-microservice:latest
    container_name: soa-payment-microservice
    ports:
      - "8083:8083"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-payment-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka

  soa-order-detail-microservice:
    image: teuzed/soa-order-detail-microservice:latest
    container_name: soa-order-detail-microservice
    ports:
      - "8084:8084"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-order-detail-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka

  soa-order-microservice:
    image: teuzed/soa-order-microservice:latest
    container_name: soa-order-microservice
    ports:
      - "8082:8082"
    networks:
      - soa-network
    environment:
      - SERVICE_SOA=soa-order-microservice
      - EUREKA_SERVER=http://soa-eureka-server:8761/eureka


networks:
  soa-network:
    driver: bridge