services:
  db-soa:
    image: mysql:8.0.33-oraclelinux8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: U20243502
      MYSQL_DATABASE: db_soa_product_microservice
      MYSQL_USER: root
      MYSQL_PASSWORD: U20243502
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - soa-network

  soa-eureka-server:
    image: teuzed/soa-eureka-server:latest
    container_name: soa-eureka-server
    ports:
      - "8761:8761"
    networks:
      - soa-network
    environment:
      - EUREKA_SERVER_PORT=8761

  soa-gateway-microservice:
    image: teuzed/soa-gateway-microservice:latest
    container_name: soa-gateway-microservice
    ports:
      - "8099:8099"
    networks:
      - soa-network
    depends_on:
      - soa-eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

  soa-product-microservice:
    image: teuzed/soa-product-microservice:latest
    container_name: soa-product-microservice
    ports:
      - "8084:8084"
    networks:
      - soa-network
    depends_on:
      - soa-eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-soa:3306/db_soa_product_microservice?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=U20243502

#  soa-order-microservice:
#    image: teuzed/soa-order-microservice:latest
#    container_name: soa-order-microservice
#    ports:
#      - "8081:8081"
#    networks:
#      - soa-network
#    depends_on:
#      - soa-eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
#      - EUREKA_INSTANCE_PREFERIPADDRESS=true

#  soa-order_detail-microservice:
#    image: teuzed/soa-order_detail-microservice:latest
#    container_name: soa-order_detail-microservice
#    ports:
#      - "8082:8082"
#    networks:
#      - soa-network
#    depends_on:
#      - soa-eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
#      - EUREKA_INSTANCE_PREFERIPADDRESS=true

#  soa-payment-microservice:
#    image: teuzed/soa-payment-microservice:latest
#    container_name: soa-payment-microservice
#    ports:
#      - "8083:8083"
#    networks:
#      - soa-network
#    depends_on:
#      - soa-eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
#      - EUREKA_INSTANCE_PREFERIPADDRESS=true

#  soa-user-microservice:
#    image: teuzed/soa-user-microservice:latest
#    container_name: soa-user-microservice
#    ports:
#      - "8085:8085"
#    networks:
#      - soa-network
#    depends_on:
#      - soa-eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://soa-eureka-server:8761/eureka/
#      - EUREKA_INSTANCE_PREFERIPADDRESS=true

networks:
  soa-network:
    driver: bridge
