spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_soa_user_microservice?useSSL=false
    username: root
    password: U20243052
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  application:
    name: soa-user-microservice

server:
  port: 8085


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /soa-user-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-user-microservice/swagger-ui.html
