

spring:
  application:
    name: soa-user-microservice

server:
  port: 8085

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


springdoc:
  api-docs:
    enabled: true
    path: /soa-user-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-user-microservice/swagger-ui.html