spring:
  application:
    name: soa-order_detail-microservice

server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /soa-order_detail-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-order_detail-microservice/swagger-ui.html