spring:
  datasource:
    url: jdbc:mysql://railway_root:XYVXcVtpUFqeCWNAZkTKmJoGkpFTtzbj@junction.proxy.rlwy.net:29885/railway
    username: railway_root
    password: XYVXcVtpUFqeCWNAZkTKmJoGkpFTtzbj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  application:
    name: soa-payment-microservice

server:
  port: 8083

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /soa-payment-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-payment-microservice/swagger-ui.html