eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761

spring:
    application:
        name: soa-eureka-server
    cloud:
        config:
        override-system-properties: yes