spring:
  application:
    name: soa-order-microservice

server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka