spring:
  datasource:
    url: jdbc:mysql://railway_root:XYVXcVtpUFqeCWNAZkTKmJoGkpFTtzbj@junction.proxy.rlwy.net:29885/railway
    username: railway_root
    password: XYVXcVtpUFqeCWNAZkTKmJoGkpFTtzbj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  application:
    name: soa-product-microservice

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


config:
  url-config:
    api_gateway: http://localhost:8099


springdoc:
  api-docs:
    enabled: true
    path: /soa-product-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-product-microservice/swagger-ui.html

app:
  version: 1.0.1




