spring:
  application:
    name: soa-product-microservice

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


config:
  url-config:
    api_gateway: http://localhost:8099


springdoc:
  api-docs:
    enabled: true
    path: /soa-product-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-product-microservice/swagger-ui.html

app:
  version: 1.0.1

