spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: soa-order-microservice
          uri: lb:http://SOA-ORDER-MICROSERVICE
          predicates:
            - Path=/api/v1/order/**
  application:
    name: soa-gateway-microservice

server:
  port: 8099




