name: Build and Push Docker Image - USER MICROSERVICE

on:
  push:
    branches:
      - develop
    paths:
      - 'soa-user-microservice/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'soa-user-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd soa-user-microservice
          docker build -t teuzed/soa-user-microservice:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push teuzed/soa-user-microservice:${{ github.sha }}
