name: Build and Publish Spring Boot Image 

on:
  push:
    branches:
      - develop
    paths:
      - 'soa-product-microservice/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'soa-product-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Spring Boot Image
        id: build
        uses: teheidoma/spring-boot-image-build-action@0.0.3
        with:
          jdk_dist: '17.0.10-graal'
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
          registry_hostname: 'docker.io'
          include_commit_sha: 'true'
      - name: Upload Image to Registry
        run: echo "Upload image ${{ steps.build.outputs.tag }}:${{ steps.build.outputs.image_tag }} to registry."
