name: Build and Push Docker Image - EUREKA MICROSERVICE

on:
  push:
    branches:
      - develop
    paths:
      - 'soa-eureka-microservice/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'soa-eureka-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd soa-eureka-microservice
          SHORT_SHA=${GITHUB_SHA::7}
          docker build -t teuzed/soa-eureka-microservice:latest -t teuzed/soa-eureka-microservice:${SHORT_SHA} .

      - name: Push Docker Images
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker push teuzed/soa-eureka-microservice:latest
          docker push teuzed/soa-eureka-microservice:${SHORT_SHA}
