name: Build and Test soa-user-microservice 

on:
  push:
    branches:
      - develop
    paths:
      - 'soa-product-microservice/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'soa-product-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd soa-user-microservice
          mvn clean package

      - name: Run tests
        run: |
          cd soa-user-microservice
          mvn test

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: soa-product-microservice-jar
          path: soa-product-microservice/target/*.jar

      - name: Get version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          cd soa-product-microservice
          docker build --build-arg JAR_VERSION=${{ env.VERSION }} -t teuzed/soa-product-microservice:${{ env.VERSION }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push teuzed/soa-product-microservice:${{ env.VERSION }}
