name: Build and Test soa-user-microservice

on:
  push:
    branches:
      - develop
    paths:
      - 'soa-user-microservice/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'soa-user-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd soa-user-microservice
          mvn clean package

      - name: Run tests
        run: |
          cd soa-user-microservice
          mvn test

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: soa-user-microservice-jar
          path: soa-user-microservice/target/*.jar
